name: flutter_ume_plus
description: UME is an in-app debug kits platform for Flutter apps. Produced by Flutter Infra team of ByteDance.
version: 4.3.0
homepage: https://github.com/mdddj/flutter_ume
repository: https://github.com/mdddj/flutter_ume

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.5.3
  vm_service: ^15.0.2
  tuple: ^2.0.2

dev_dependencies:
  mockito: ^5.5.1
  lints: ^6.0.0
  flutter_lints: ^6.0.0


