name: flutter_ume_kit_channel_monitor_plus
description: channel monitor kit for flutter_ume
version: 4.3.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume_plus: ^4.3.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^6.0.0

