name: flutter_ume_kit_perf_plus
description: Performance kits for flutter_ume.
version: 4.3.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  vm_service: ^15.0.2
  flutter_ume_plus: ^4.3.0

dev_dependencies:
  mockito: ^5.5.1

