name: flutter_ume_kit_console_plus
description: Show debugPrint kit for flutter_ume.
version: 5.0.0
homepage: https://github.com/mdddj/flutter_ume
repository: https://github.com/mdddj/flutter_ume

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.2
  shared_preferences: ^2.5.4
  flutter_ume_plus: ^5.0.0
  share_plus: ^12.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  mockito: ^5.6.1
  flutter_lints: ^6.0.0

