name: flutter_ume_kit_console_plus
description: Show debugPrint kit for flutter_ume.
version: 4.3.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.2
  shared_preferences: ^2.5.3
  flutter_ume_plus: ^4.3.0
  share_plus: ^12.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  mockito: ^5.5.1
  flutter_lints: ^6.0.0

