name: flutter_ume_kit_show_code_plus
description: Show Code kit for flutter_ume.
version: 4.3.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_ume_plus: ^4.3.0
  share_plus: ^12.0.0
  vm_service: ^15.0.2
  string_scanner: ^1.4.1
dev_dependencies:
  mockito: ^5.5.1
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

