name: flutter_ume_kit_show_code_plus
description: Show Code kit for flutter_ume.
version: 5.0.0
homepage: https://github.com/mdddj/flutter_ume
repository: https://github.com/mdddj/flutter_ume

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_ume_plus: ^5.0.0
  share_plus: ^12.0.0
  vm_service: ^15.0.2
  string_scanner: ^1.4.1
dev_dependencies:
  mockito: ^5.5.1

