name: flutter_ume_kit_ui_plus
description: UI Kits for flutter_ume_plus.
version: 4.4.1
homepage: https://github.com/mdddj/flutter_ume
repository: https://github.com/mdddj/flutter_ume

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume_plus: ^4.4.1
  touch_indicator: ^2.0.0
  image: ^4.5.4
  quiver: ^3.2.2
  basics: ^0.10.0

dev_dependencies:
  mockito: ^5.6.1
  flutter_lints: ^6.0.0

