name: flutter_ume_kit_ui_plus
description: UI Kits for flutter_ume_plus.
version: 4.3.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume_plus: ^4.3.0
  touch_indicator: ^2.0.0
  image: ^4.5.4
  quiver: ^3.2.2
  basics: ^0.10.0

dev_dependencies:
  mockito: ^5.5.1
  flutter_lints: ^6.0.0
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

