name: flutter_ume_kit_shared_preferences_plus
description: SharedPreferences viewer and editor kit for flutter_ume. View, edit, search and delete SharedPreferences data.
version: 1.0.0
homepage: https://github.com/mdddj/flutter_ume
repository: https://github.com/mdddj/flutter_ume

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_ume_plus: ^4.4.1
  shared_preferences: ^2.5.4
  tuple: ^2.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
