name: flutter_ume_kit_dio_plus
description: Dio kit for flutter_ume.
version: 3.0.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume: ^1.1.2
  dio: ^5.3.2
  flutter_json_view: ^1.1.3
  flutter_json_viewer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
